import { useState } from 'react';
import type { Block } from '../../types';
import styles from './ChainAnalytics.module.css';

interface ChainAnalyticsProps {
  blocks: Block[];
  onSelectBlock?: (blockId: number) => void;
}

interface HoveredPoint {
  blockId: number;
  nonce: number;
  attempts: number;
  durationMs: number;
  status: string;
}

export default function ChainAnalytics({ blocks, onSelectBlock }: ChainAnalyticsProps) {
  const [hoveredData, setHoveredData] = useState<HoveredPoint | null>(null);

  const totalBlocks = blocks.length;
  const minedBlocks = blocks.filter(b => b.isMined && b.isValid);
  const minedCount = minedBlocks.length;
  const allMined = minedCount === totalBlocks && totalBlocks > 0;
  const hasInvalid = blocks.some(b => !b.isValid && (b.isMined || b.nonce > 0));

  const totalAttempts = blocks.reduce(
    (acc, b) => acc + (b.miningAttempts || (b.isMined ? b.nonce + 1 : 0)),
    0
  );

  const avgNonce =
    minedCount > 0
      ? Math.round(minedBlocks.reduce((acc, b) => acc + b.nonce, 0) / minedCount)
      : 0;

  const avgDurationMs =
    minedCount > 0
      ? Math.round(
          minedBlocks.reduce((acc, b) => acc + (b.miningDurationMs || 0), 0) / minedCount
        )
      : 0;

  // Chart dimensions & scaling
  const chartWidth = 460;
  const chartHeight = 150;
  const padding = { top: 20, right: 20, bottom: 30, left: 45 };
  const innerWidth = chartWidth - padding.left - padding.right;
  const innerHeight = chartHeight - padding.top - padding.bottom;

  // Max values for scales
  const maxNonce = Math.max(100, ...blocks.map(b => b.nonce));
  const maxAttempts = Math.max(100, ...blocks.map(b => b.miningAttempts || b.nonce + 1));

  const getX = (index: number) => {
    if (totalBlocks <= 1) return innerWidth / 2;
    return (index / (totalBlocks - 1)) * innerWidth;
  };

  const getBarX = (index: number) => {
    const slotWidth = innerWidth / totalBlocks;
    const barWidth = Math.min(32, slotWidth * 0.6);
    return index * slotWidth + (slotWidth - barWidth) / 2;
  };

  const getBarWidth = () => {
    const slotWidth = innerWidth / totalBlocks;
    return Math.min(32, slotWidth * 0.6);
  };

  return (
    <section className={styles.analyticsContainer} aria-label="Chain Analytics Dashboard">
      <div className={styles.header}>
        <p className={styles.label}>Real-Time Metrics</p>
        <h2 className={styles.title}>Chain Analytics</h2>
        <p className={styles.subtitle}>
          Observe the cryptographic workload, nonce distribution, and execution metrics
          generated by the active blockchain state.
        </p>
      </div>

      {/* Summary Stat Cards */}
      <div className={styles.statGrid}>
        <div className={styles.statCard}>
          <span className={styles.statLabel}>Total Blocks</span>
          <span className={styles.statValue}>
            {String(totalBlocks).padStart(2, '0')}
          </span>
          <span className={styles.statSubtext}>Current chain length</span>
        </div>

        <div className={styles.statCard}>
          <span className={styles.statLabel}>Mined Status</span>
          <span
            className={styles.statValue}
            style={{
              color: allMined
                ? 'var(--color-valid)'
                : hasInvalid
                ? 'var(--color-invalid)'
                : 'var(--color-text-primary)',
            }}
          >
            {minedCount} / {totalBlocks}
          </span>
          <span className={styles.statSubtext}>
            {allMined ? 'All blocks verified' : hasInvalid ? 'Compromised state' : 'Pending mining'}
          </span>
        </div>

        <div className={styles.statCard}>
          <span className={styles.statLabel}>Total SHA-256 Iterations</span>
          <span className={styles.statValue}>
            {totalAttempts.toLocaleString()}
          </span>
          <span className={styles.statSubtext}>Total proof of work hashes</span>
        </div>

        <div className={styles.statCard}>
          <span className={styles.statLabel}>Average Nonce / Time</span>
          <span className={styles.statValue}>
            {avgNonce.toLocaleString()}{' '}
            <span style={{ fontSize: 'var(--text-sm)', color: 'var(--color-text-tertiary)' }}>
              ({avgDurationMs}ms)
            </span>
          </span>
          <span className={styles.statSubtext}>Mean iterations per block</span>
        </div>
      </div>

      {/* Charts Grid */}
      <div className={styles.chartsGrid}>
        {/* Graph 1: Nonce by Block */}
        <div className={styles.chartCard}>
          <div className={styles.chartHeader}>
            <span className={styles.chartTitle}>Nonce Distribution</span>
            <span className={styles.chartBadge}>Iterations to &ldquo;00&rdquo;</span>
          </div>

          <div className={styles.svgWrapper}>
            <svg
              className={styles.svgChart}
              viewBox={`0 0 ${chartWidth} ${chartHeight}`}
              preserveAspectRatio="xMidYMid meet"
              aria-label="Nonce values per block chart"
            >
              {/* Grid Lines */}
              <line
                x1={padding.left}
                y1={padding.top}
                x2={padding.left + innerWidth}
                y2={padding.top}
                stroke="var(--color-border)"
                strokeDasharray="3 3"
              />
              <line
                x1={padding.left}
                y1={padding.top + innerHeight / 2}
                x2={padding.left + innerWidth}
                y2={padding.top + innerHeight / 2}
                stroke="var(--color-border)"
                strokeDasharray="3 3"
              />
              <line
                x1={padding.left}
                y1={padding.top + innerHeight}
                x2={padding.left + innerWidth}
                y2={padding.top + innerHeight}
                stroke="var(--color-border)"
              />

              {/* Y-Axis Labels */}
              <text
                x={padding.left - 8}
                y={padding.top + 4}
                fill="var(--color-text-tertiary)"
                fontSize="10"
                fontFamily="var(--font-mono)"
                textAnchor="end"
              >
                {maxNonce}
              </text>
              <text
                x={padding.left - 8}
                y={padding.top + innerHeight / 2 + 4}
                fill="var(--color-text-tertiary)"
                fontSize="10"
                fontFamily="var(--font-mono)"
                textAnchor="end"
              >
                {Math.round(maxNonce / 2)}
              </text>
              <text
                x={padding.left - 8}
                y={padding.top + innerHeight + 4}
                fill="var(--color-text-tertiary)"
                fontSize="10"
                fontFamily="var(--font-mono)"
                textAnchor="end"
              >
                0
              </text>

              {/* Polyline Path connecting mined nonces */}
              {minedCount > 1 && (
                <path
                  d={blocks
                    .map((b, i) => {
                      const x = padding.left + getX(i);
                      const y =
                        padding.top +
                        innerHeight -
                        (b.nonce / maxNonce) * innerHeight;
                      return `${i === 0 ? 'M' : 'L'} ${x} ${y}`;
                    })
                    .join(' ')}
                  fill="none"
                  stroke="var(--color-accent-blue)"
                  strokeWidth="2"
                  opacity="0.6"
                />
              )}

              {/* Data Points */}
              {blocks.map((b, i) => {
                const x = padding.left + getX(i);
                const y =
                  padding.top +
                  innerHeight -
                  (b.nonce / maxNonce) * innerHeight;
                const isHovered = hoveredData?.blockId === b.id;
                const pointColor = b.isValid
                  ? 'var(--color-valid)'
                  : b.isMined
                  ? 'var(--color-invalid)'
                  : 'var(--color-text-tertiary)';

                return (
                  <g
                    key={b.id}
                    style={{ cursor: 'pointer' }}
                    onClick={() => onSelectBlock?.(b.id)}
                    onMouseEnter={() =>
                      setHoveredData({
                        blockId: b.id,
                        nonce: b.nonce,
                        attempts: b.miningAttempts || b.nonce + 1,
                        durationMs: b.miningDurationMs || 0,
                        status: b.isValid ? 'VALID' : b.isMined ? 'INVALID' : 'UNMINED',
                      })
                    }
                    onMouseLeave={() => setHoveredData(null)}
                  >
                    <circle
                      cx={x}
                      cy={y}
                      r={isHovered ? 6 : 4.5}
                      fill={pointColor}
                      stroke="var(--color-bg-primary)"
                      strokeWidth="2"
                      style={{ transition: 'all var(--transition-fast)' }}
                    />
                    {/* X-Axis Label */}
                    <text
                      x={x}
                      y={chartHeight - 6}
                      fill={isHovered ? 'var(--color-text-primary)' : 'var(--color-text-tertiary)'}
                      fontSize="10"
                      fontFamily="var(--font-mono)"
                      textAnchor="middle"
                    >
                      B{b.id}
                    </text>
                  </g>
                );
              })}
            </svg>

            {hoveredData && (
              <div className={styles.tooltipHud}>
                <div className={styles.tooltipTitle}>Block {hoveredData.blockId}</div>
                <div className={styles.tooltipRow}>
                  <span>Nonce:</span>
                  <span className={styles.tooltipVal}>{hoveredData.nonce}</span>
                </div>
                <div className={styles.tooltipRow}>
                  <span>Attempts:</span>
                  <span className={styles.tooltipVal}>{hoveredData.attempts}</span>
                </div>
                <div className={styles.tooltipRow}>
                  <span>Status:</span>
                  <span
                    className={styles.tooltipVal}
                    style={{
                      color:
                        hoveredData.status === 'VALID'
                          ? 'var(--color-valid)'
                          : hoveredData.status === 'INVALID'
                          ? 'var(--color-invalid)'
                          : 'var(--color-text-tertiary)',
                    }}
                  >
                    {hoveredData.status}
                  </span>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Graph 2: Hash Attempts per Block (Bar Chart) */}
        <div className={styles.chartCard}>
          <div className={styles.chartHeader}>
            <span className={styles.chartTitle}>Computational Work</span>
            <span className={styles.chartBadge}>SHA-256 Hashes Executed</span>
          </div>

          <div className={styles.svgWrapper}>
            <svg
              className={styles.svgChart}
              viewBox={`0 0 ${chartWidth} ${chartHeight}`}
              preserveAspectRatio="xMidYMid meet"
              aria-label="SHA-256 hash attempts per block chart"
            >
              {/* Grid Lines */}
              <line
                x1={padding.left}
                y1={padding.top}
                x2={padding.left + innerWidth}
                y2={padding.top}
                stroke="var(--color-border)"
                strokeDasharray="3 3"
              />
              <line
                x1={padding.left}
                y1={padding.top + innerHeight}
                x2={padding.left + innerWidth}
                y2={padding.top + innerHeight}
                stroke="var(--color-border)"
              />

              {/* Y-Axis Labels */}
              <text
                x={padding.left - 8}
                y={padding.top + 4}
                fill="var(--color-text-tertiary)"
                fontSize="10"
                fontFamily="var(--font-mono)"
                textAnchor="end"
              >
                {maxAttempts}
              </text>
              <text
                x={padding.left - 8}
                y={padding.top + innerHeight + 4}
                fill="var(--color-text-tertiary)"
                fontSize="10"
                fontFamily="var(--font-mono)"
                textAnchor="end"
              >
                0
              </text>

              {/* Bars */}
              {blocks.map((b, i) => {
                const attempts = b.miningAttempts || (b.isMined ? b.nonce + 1 : 0);
                const barHeight = Math.max(
                  4,
                  (attempts / maxAttempts) * innerHeight
                );
                const x = padding.left + getBarX(i);
                const y = padding.top + innerHeight - barHeight;
                const barWidth = getBarWidth();
                const isHovered = hoveredData?.blockId === b.id;

                const fillColor = b.isValid
                  ? 'var(--color-accent-blue)'
                  : b.isMined
                  ? 'var(--color-invalid)'
                  : 'var(--color-bg-tertiary)';

                return (
                  <g
                    key={b.id}
                    style={{ cursor: 'pointer' }}
                    onClick={() => onSelectBlock?.(b.id)}
                    onMouseEnter={() =>
                      setHoveredData({
                        blockId: b.id,
                        nonce: b.nonce,
                        attempts,
                        durationMs: b.miningDurationMs || 0,
                        status: b.isValid ? 'VALID' : b.isMined ? 'INVALID' : 'UNMINED',
                      })
                    }
                    onMouseLeave={() => setHoveredData(null)}
                  >
                    <rect
                      x={x}
                      y={y}
                      width={barWidth}
                      height={barHeight}
                      rx={3}
                      fill={fillColor}
                      opacity={isHovered ? 1 : 0.8}
                      style={{ transition: 'all var(--transition-fast)' }}
                    />
                    <text
                      x={x + barWidth / 2}
                      y={chartHeight - 6}
                      fill={isHovered ? 'var(--color-text-primary)' : 'var(--color-text-tertiary)'}
                      fontSize="10"
                      fontFamily="var(--font-mono)"
                      textAnchor="middle"
                    >
                      B{b.id}
                    </text>
                  </g>
                );
              })}
            </svg>
          </div>
        </div>
      </div>
    </section>
  );
}
